// Mocks generated by Mockito 5.0.7 from annotations
// in star_wars/test/film_provider_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:star_wars/models/films_model.dart' as _i2;
import 'package:star_wars/services/film_service.dart' as _i3;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

class _FakeFilmsModel extends _i1.Fake implements _i2.FilmsModel {}

/// A class which mocks [FilmService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFilmService extends _i1.Mock implements _i3.FilmService {
  MockFilmService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.FilmsModel> getFilm(dynamic url) =>
      (super.noSuchMethod(Invocation.method(#getFilm, [url]),
              returnValue: Future<_i2.FilmsModel>.value(_FakeFilmsModel()))
          as _i4.Future<_i2.FilmsModel>);
}
