// Mocks generated by Mockito 5.0.7 from annotations
// in star_wars/test/people_provider_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:star_wars/models/people_paginated_model.dart' as _i2;
import 'package:star_wars/services/people_service.dart' as _i3;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

class _FakePeoplePaginatedModel extends _i1.Fake
    implements _i2.PeoplePaginatedModel {}

/// A class which mocks [PeopleService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPeopleService extends _i1.Mock implements _i3.PeopleService {
  MockPeopleService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.PeoplePaginatedModel> getAll(int? page) =>
      (super.noSuchMethod(Invocation.method(#getAll, [page]),
              returnValue: Future<_i2.PeoplePaginatedModel>.value(
                  _FakePeoplePaginatedModel()))
          as _i4.Future<_i2.PeoplePaginatedModel>);
}
